/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApoiadoresRouteImport } from './routes/apoiadores'
import { Route as ColaboreRouteImport } from './routes/colabore'
import { Route as ProjetoRouteImport } from './routes/projeto'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoiadoresRoute = ApoiadoresRouteImport.update({
  id: '/apoiadores',
  path: '/apoiadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboreRoute = ColaboreRouteImport.update({
  id: '/colabore',
  path: '/colabore',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoRoute = ProjetoRouteImport.update({
  id: '/projeto',
  path: '/projeto',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apoiadores': typeof ApoiadoresRoute
  '/colabore': typeof ColaboreRoute
  '/projeto': typeof ProjetoRoute
  '/servicos': typeof ServicosRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apoiadores': typeof ApoiadoresRoute
  '/colabore': typeof ColaboreRoute
  '/projeto': typeof ProjetoRoute
  '/servicos': typeof ServicosRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apoiadores': typeof ApoiadoresRoute
  '/colabore': typeof ColaboreRoute
  '/projeto': typeof ProjetoRoute
  '/servicos': typeof ServicosRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/apoiadores' | '/colabore' | '/projeto' | '/servicos' | '/sobre-nos'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/apoiadores' | '/colabore' | '/projeto' | '/servicos' | '/sobre-nos'
  id:
    | '__root__'
    | '/'
    | '/apoiadores'
    | '/colabore'
    | '/projeto'
    | '/servicos'
    | '/sobre-nos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApoiadoresRoute: typeof ApoiadoresRoute
  ColaboreRoute: typeof ColaboreRoute
  ProjetoRoute: typeof ProjetoRoute
  ServicosRoute: typeof ServicosRoute
  SobreNosRoute: typeof SobreNosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoiadores': {
      id: '/apoiadores'
      path: '/apoiadores'
      fullPath: '/apoiadores'
      preLoaderRoute: typeof ApoiadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colabore': {
      id: '/colabore'
      path: '/colabore'
      fullPath: '/colabore'
      preLoaderRoute: typeof ColaboreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto': {
      id: '/projeto'
      path: '/projeto'
      fullPath: '/projeto'
      preLoaderRoute: typeof ProjetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApoiadoresRoute: ApoiadoresRoute,
  ColaboreRoute: ColaboreRoute,
  ProjetoRoute: ProjetoRoute,
  ServicosRoute: ServicosRoute,
  SobreNosRoute: SobreNosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
